apiVersion: v1
kind: Service
metadata:
  name: waf-killer
  labels:
    app: waf-killer
spec:
  type: ClusterIP
  sessionAffinity: ClientIP # Sticky sessions
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: http-api
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: waf-killer
---
apiVersion: v1
kind: Service
metadata:
  name: waf-killer-metrics
  labels:
    app: waf-killer
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: waf-killer
